#!/bin/sh
# Clemens Gruber, 2013
# Set up symbolic links to dotfile dirs

# ZSH
ln -s $(pwd)/zshrc $HOME/.zshrc

# Emacs
ln -s $(pwd)/emacs/ $HOME/.emacs.d

# Vim
ln -s $(pwd)/vim $HOME/.vim
ln -s $(pwd)/vimrc $HOME/.vimrc
