#!/bin/sh
# Clemens Gruber, 2012
# Set up symbolic links to dotfile dirs

# ZSH
ln -s $(pwd)/zsh/zshrc $HOME/.zshrc
ln -s $(pwd)/zsh/zshenv $HOME/.zshenv
ln -s $(pwd)/zsh/zlogin $HOME/.zlogin

# Emacs
ln -s $(pwd)/emacs $HOME/.emacs.d

# Vim
ln -s $(pwd)/vimrc $HOME/.vimrc
