#!/bin/bash
# Clemens Gruber, 2015
# Config setup
#

echo -n "Initializing config dirs and linking files... "

# Create directories
mkdir -p $HOME/.history

# Git
ln -s -f $(pwd)/gitconfig $HOME/.gitconfig
ln -s -f $(pwd)/gitignore $HOME/.gitignore

# ZSH
ln -s -f $(pwd)/zshrc $HOME/.zshrc

# Emacs
ln -s -f $(pwd)/emacs $HOME/.emacs

# Vim
ln -s -f $(pwd)/vimrc $HOME/.vimrc

# SSH
mkdir -p $HOME/.ssh
if [ ! -f $HOME/.ssh/config ]; then
    cp $(pwd)/ssh_config_default $HOME/.ssh/config
fi

# tmux
ln -s -f $(pwd)/tmux.conf $HOME/.tmux.conf
if [ "$(uname)" == "Darwin" ]; then
  ln -s -f $(pwd)/tmux-osx.conf $HOME/.tmux-osx.conf
fi

# Others
ln -s -f $(pwd)/agignore $HOME/.agignore
ln -s -f $(pwd)/gdbinit $HOME/.gdbinit
ln -s -f $(pwd)/gemrc $HOME/.gemrc
ln -s -f $(pwd)/irbrc $HOME/.irbrc
ln -s -f $(pwd)/psqlrc $HOME/.psqlrc
ln -s -f $(pwd)/sqliterc $HOME/.sqliterc
ln -s -f $(pwd)/valgrindrc $HOME/.valgrindrc

echo "OK"
