#!/bin/sh
#
# ~/.xinitrc
#
# Executed by startx (run your window manager from here)

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# update x resource db
xrdb -merge ~/.Xresources

# start xscreensaver daemon
xscreensaver -no-splash &

# set cursor icon
xsetroot -cursor_name left_ptr &

# set background image
sh ~/.fehbg &

# disable trackpad during typing
nohup syndaemon -R -t -k -i 2 &

# start awesome window manager
exec awesome
