ZSH=$HOME/.oh-my-zsh
ZSH_THEME="robbyrussell"
# Set to this to use case-sensitive completion
# CASE_SENSITIVE="true"
# Uncomment this to disable weekly auto-update checks
# DISABLE_AUTO_UPDATE="true"
# Uncomment to change how often before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=6
# Uncomment following line if you want to disable colors in ls
# DISABLE_LS_COLORS="true"
# Uncomment following line if you want to disable autosetting terminal title.
# DISABLE_AUTO_TITLE="true"
# Uncomment following line if you want to disable command autocorrection
# DISABLE_CORRECTION="true"
# Uncomment following line if you want red dots to be displayed while waiting for completion
# COMPLETION_WAITING_DOTS="true"
# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"
# Uncomment following line if you want to  shown in the command execution time stamp 
# in the history command output. The optional three formats: "mm/dd/yyyy"|"dd.mm.yyyy"|
# yyyy-mm-dd
HIST_STAMPS="dd.mm.yyyy"

# zsh tmux plugin config
ZSH_TMUX_AUTOSTART=false
ZSH_TMUX_ITERM2=false

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
plugins=(git bundler tmux)
# Contains only platform-independent plugins, platform-dependent plugins are added below

DOTFILES=$HOME/dotfiles

# Detect platform
source $DOTFILES/zsh/os.zsh
# Load platform-specific configurations (and oh-my-zsh plugins!)
[[ -s "$DOTFILES/zsh/os/$PLATFORM.zsh" ]] && source "$DOTFILES/zsh/os/$PLATFORM.zsh"
typeset -U plugins

# Load oh-my-zsh
source $ZSH/oh-my-zsh.sh

# Cocoapods needs LC_CTYPE to be set
export LC_CTYPE="en_US.UTF-8"
# Homebrew: PATH and MANPATH
export MANPATH="/usr/local/man:/usr/local/share/man:/usr/man:/usr/share/man:$MANPATH"
export PATH="/usr/local/bin:/usr/local/sbin:$PATH"

# RVM
if [[ -d "$HOME/.rvm" ]]; then
  PATH=$PATH:$HOME/.rvm/bin
fi

# Set $EMACS variable to launch emacsclient with a daemon
source $DOTFILES/zsh/emacsclient.zsh

# Aliases
alias dr="$DOTFILES/scripts/daily_routine.sh"
alias e=$EMACS
alias v=$VIM

# Reminders if not using the shortest aliases
alias emacs='echo "Hey! Next time, type e instead of emacs"; $EMACS'
alias vim='echo "Hey! Next time, type v instead of vim"; $VIM'

# Finally set favorite editor
export EDITOR=$EMACS
#export EDITOR=$VIM

# Git soll MacVim im Konsolenmodus nehmen
export GIT_EDITOR=mvimc

# Remove duplicates from PATH, etc.
typeset -U PATH
typeset -U MANPATH
