# Path to your oh-my-zsh configuration.
ZSH=$HOME/.oh-my-zsh

# Set name of the theme to load.
# Look in ~/.oh-my-zsh/themes/
# Optionally, if you set this to "random", it'll load a random theme each
# time that oh-my-zsh is loaded.
ZSH_THEME="rkj"

# Uncomment to change how often before auto-updates occur? (in days)
export UPDATE_ZSH_DAYS=6

# Uncomment following line if you want to disable marking untracked files under
# VCS as dirty. This makes repository status check for large repositories much,
# much faster.
# DISABLE_UNTRACKED_FILES_DIRTY="true"

# Disable oh-my-zsh title updating for tmux
#export DISABLE_AUTO_TITLE=true

# Which plugins would you like to load? (plugins can be found in ~/.oh-my-zsh/plugins/*)
# Custom plugins may be added to ~/.oh-my-zsh/custom/plugins/
# Example format: plugins=(rails git textmate ruby lighthouse)
plugins=(git)

source $ZSH/oh-my-zsh.sh

## Custom

DOTFILES=$HOME/Dev/dotfiles

# Detect platform
source $DOTFILES/zsh/os-detect.zsh
# Load platform-specific configurations
[[ -s "$DOTFILES/zsh/os/$PLATFORM.zsh" ]] && source "$DOTFILES/zsh/os/$PLATFORM.zsh"

# Override upgrade_oh_my_zsh to pull upstream changes
function upgrade_oh_my_zsh() {
  /usr/bin/env ZSH=$ZSH /bin/sh $DOTFILES/tools/upgrade.sh
}

# Load rbenv if available
if which rbenv > /dev/null
then
  export PATH=$PATH:$HOME/.rbenv/bin
  eval "$(rbenv init -)"
fi
